# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdiUp129nV5hf3IdPl1oquv2B4N8Fxho
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

filename = list(uploaded.keys())[0]

data = pd.read_csv(filename)

print("Dataset loaded successfully!")
print("Rows:", data.shape[0])
print("Columns:", data.shape[1])

data.head()

import ipywidgets as widgets
from IPython.display import display

columns = list(data.columns)

sensitive_dropdown = widgets.Dropdown(
    options=columns,
    description='Sensitive:'
)

outcome_dropdown = widgets.Dropdown(
    options=columns,
    description='Outcome:'
)

display(sensitive_dropdown)
display(outcome_dropdown)

from fairlearn.metrics import demographic_parity_difference
import matplotlib.pyplot as plt

sensitive_col = sensitive_dropdown.value
outcome_col = outcome_dropdown.value

print("Sensitive Attribute:", sensitive_col)
print("Outcome Column:", outcome_col)

audit_data = data.copy()

# Convert outcome to binary
def convert_outcome(x):

    x = str(x).lower()

    if x in ["good", "approved", "yes", "1", "true"]:
        return 1

    return 0

audit_data["Outcome_Binary"] = audit_data[outcome_col].apply(convert_outcome)

approval_rates = (
    audit_data
    .groupby(sensitive_col)["Outcome_Binary"]
    .mean()
)

print("\nApproval Rates")
print(approval_rates)

dp = demographic_parity_difference(
    y_true=audit_data["Outcome_Binary"],
    y_pred=audit_data["Outcome_Binary"],
    sensitive_features=audit_data[sensitive_col]
)

print("\nDemographic Parity Difference:", round(dp,4))

import matplotlib.pyplot as plt

approval_rates.plot(kind="bar")

plt.title("Approval Rate by Group")
plt.xlabel(sensitive_col)
plt.ylabel("Approval Rate")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

counts = pd.crosstab(
    audit_data[sensitive_col],
    audit_data[outcome_col]
)

counts.plot(kind="bar")

plt.title("Outcome Distribution by Group")
plt.xlabel(sensitive_col)
plt.ylabel("Count")

plt.show()

print("="*50)
print("AI BIAS AUDIT REPORT")
print("="*50)

print("\nSensitive Attribute:")
print(sensitive_col)

print("\nOutcome Column:")
print(outcome_col)

print("\nApproval Rates:")
print(approval_rates)

print("\nDemographic Parity Difference:")
print(round(dp,4))

if dp < 0.05:
    print("\nAssessment:")
    print("Low evidence of bias detected.")
elif dp < 0.10:
    print("\nAssessment:")
    print("Moderate disparity detected.")
else:
    print("\nAssessment:")
    print("Significant disparity detected.")

print("\nAudit Complete.")